Don't stop testing examples when one fails and upload artifacts for debugging purposes.

diff --git a/.github/workflows/make.yml b/.github/workflows/make.yml
--- a/.github/workflows/make.yml
+++ b/.github/workflows/make.yml
@@ -164,6 +164,12 @@ jobs:
         run: make -j4 -C ${{env.CEDEV_EXAMPLES}} COMPRESSED=${{matrix.compressed}} V=1 gfx
       - name: Build Examples
         run: make -j4 -C ${{env.CEDEV_EXAMPLES}} COMPRESSED=${{matrix.compressed}} V=1
+      - name: Upload Example Build Artifacts
+        uses: actions/upload-artifact@v2
+        if: always()
+        with:
+          name: examples-${{runner.os}}
+          path: ${{env.CEDEV_EXAMPLES}}
 
       - name: Checkout CEmu
         if: github.event_name != 'pull_request'
@@ -208,14 +214,15 @@ jobs:
       - name: Test Examples
         if: github.event_name != 'pull_request' && runner.os != 'Windows'
         run: |
-          failed=0
-          find ${{env.CEDEV_EXAMPLES}} -name autotest.json -print0 | while read -d '' test; do
-            cmake -E echo "Launching autotester on $test"
-            ${{env.AUTOTESTER_PATH}}/autotester "$test"
-            cmake -E true $((failed += $?))
-          done
-          cmake -E echo "$failed tests failed"
-          exit $failed
+          find ${{env.CEDEV_EXAMPLES}} -name autotest.json -print0 | {
+            failed=0
+            while read -d '' test; do
+              cmake -E echo "Launching autotester on $test"
+              ${{env.AUTOTESTER_PATH}}/autotester "$test" || cmake -E true $((failed += $?))
+            done
+            cmake -E echo "$failed tests failed"
+            exit $failed
+          }
       - name: Test Examples
         if: github.event_name != 'pull_request' && runner.os == 'Windows'
         run: |
